name: sukientotapp
description: "Mobile application for SukienTot"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  flutter_swipe_button: ^2.1.3
  flutter_native_splash: ^2.4.7
  pull_to_refresh: ^2.0.0
  phonecodes: ^0.0.4
  carousel_slider: ^5.1.1
  dio: ^5.9.0
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  get: ^4.7.3
  get_storage: ^2.1.1
  forui: ^0.17.0
  forui_assets: ^0.17.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.1
  logger: ^2.6.2
  animations: ^2.1.1
  google_sign_in: ^7.2.0
  camera: ^0.11.3
  smooth_page_indicator: ^2.0.1
  infinite_scroll_pagination: ^5.1.1
  timeago: ^3.7.1
  badges: ^3.1.2
  mask_text_input_formatter: ^2.9.0
  animated_text_kit: ^4.3.0
  stack_trace: ^1.12.1
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^6.0.0
  font_awesome_flutter: ^10.12.0
  dio_log: ^5.3.0+3
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
